### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by huoyiru** [zhang-haojie/wesam#1]
这个工作真实太棒了，请问大概什么时候能开放代码？

**Comment by zhang-haojie** [comment]
Hello,

Thank you for your interest in our work!

As we are still refining the project, we may not be able to release the code soon. We apologize for any inconvenience.

If you are genuinely interested, please stay updated on https://github.com/zhang-haojie/wesam.git as we plan to open-source the code in the future.

Thank you,
Haojie

**Comment by zhang-haojie** [comment]
Thank you for your patience and interest in our work. We have released the code for this work. We hope it will be useful for you to follow.
