### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by Taoqi0402** [zhang-haojie/wesam#10]
Dear author, while I was running the last round of the first epoch, the following error occurred:
Traceback (most recent call last):
  File "adaptation.py", line 210, in <module>
    main(cfg)
  File "adaptation.py", line 200, in main
    train_sam(cfg, fabric, model, anchor_model, optimizer, scheduler, train_data, val_data)
  File "adaptation.py", line 53, in train_sam
    images_weak, images_strong, bboxes, gt_masks = data
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by zhang-haojie** [comment]
It seems like validation data has been called, can you check it?
