### ISSUE TITLE
possible wrong?

### ISSUE THREAD

**Issue by lfxx** [zhang-haojie/wesam#11]
```
soft_image_embeds, soft_masks, soft_iou_predictions, soft_res_masks = model(images_weak, prompts)    # teacher
pred_image_embeds, pred_masks, iou_predictions, pred_res_masks = model(images_strong, prompts)   # student
```
As teacher,images_weak may been flipped in weak transform,same as prompts.
As student,images_strong is not been flipped in strong transform.but this repo use same prompts as teacher which is not fit with images_strong.
is here some mistake?
Thank you!

**Comment by zhang-haojie** [comment]
Possible errors, I will update later. Thank you!
