### ISSUE TITLE
Input of inference

### ISSUE THREAD

**Issue by xixinzhang** [zhang-haojie/wesam#25]
Do we still need to sample prompts as input when we do the inference? In your validation code, prompts are still used as follows? 
https://github.com/zhang-haojie/wesam/blob/f3995229851e21576c2d548d7a4c6836082e152d/utils/eval_utils.py#L64
We usually don't have any info about labels when doing the inference, do we?

**Comment by zhang-haojie** [comment]
SAM is essentially a segmentation model based on prompts.

We do this for the convenience of evaluation. After all, the segmentation masks generated have corresponding 'GT'
