### ISSUE TITLE
After training with the CAMO dataset , how can I use the fine-tuned checkpoint to visualize data in the CAMO?

### ISSUE THREAD

**Issue by wanglian0701** [zhang-haojie/wesam#32]

**Comment by zhang-haojie** [comment]
You can refer to #6

**Comment by wanglian0701** [comment]
Thank you for your reply.

**Comment by wanglian0701** [comment]
full_checkpoint = fabric.load(ckpt)
model.load_state_dict(full_checkpoint["model"])
"What is “fabric.load”? I get the error AttributeError: module 'fabric' has no attribute 'load' when I run the code."

**Comment by zhang-haojie** [comment]
`fabric.load` is similar to `torch.load`. Maybe `lightning` version doesn't match. I installed `lightning==2.0.1`.
