### ISSUE TITLE
 Thank you for your research work. I would like to perform inference and visualization using the fine-tuned weights file. Could you please provide concise steps for doing so?

### ISSUE THREAD

**Issue by ybk66** [zhang-haojie/wesam#6]
Thank you for your research work. I would like to perform inference and visualization using the fine-tuned weights file. Could you please provide concise steps for doing so?

**Comment by ybk66** [comment]
感谢您所做的科研工作。我希望使用微调后的权重文件进行推理并可视化，请问能否提供简洁的操作步骤？

**Comment by zhang-haojie** [comment]
Sorry, we haven't organized the visualization code yet, so for the sake of code simplicity, we didn't upload the visualization part. If you want to perform visualization operations, here's an example using visualizing bbox:
1. Need to add returning the original image in the existing Dataset
```
origin_image = image
origin_bboxes = bboxes
origin_masks = masks
if self.transform:
    padding, image, masks, bboxes = self.transform(image, masks, np.array(bboxes), True)

bboxes = np.stack(bboxes, axis=0)
masks = np.stack(masks, axis=0)
origin_bboxes = np.stack(origin_bboxes, axis=0)
origin_masks = np.stack(origin_masks, axis=0)
return image_id, padding, origin_image, origin_bboxes, origin_masks, image, torch.tensor(bboxes), torch.tensor(masks).float()
```
2. After inferring the mask, you need to transform the mask to fit the shape of the original image.
```
base_masks_ = []
for ori_image, padding, base_mask in zip(ori_images, paddings, base_masks):
    ori_H, ori_W, C = ori_image.shape
    base_mask = base_mask.unsqueeze(1)
    base_mask = base_mask[..., padding[1] : base_mask.shape[-2] - padding[3], padding[0] : base_mask.shape[-1] - padding[2]]
    base_mask = F.interpolate(base_mask, (ori_H, ori_W), mode="bilinear", align_corners=False)
    base_masks_.append((base_mask.squeeze(1) > 0.).cpu().numpy().astype(bool))
multi_masks = [base_masks_]
```
3. Next, visualize the original image, original bbox, and segmented masks. Note that there are multiple masks here.
```
for b, (image_id, ori_image, padding, ori_mask, bbox) in enumerate(zip(
    image_ids, ori_images, paddings, origin_masks, ori_bboxes)):
    H, W, C = ori_image.shape
    n = len(multi_masks)
    fig, axs = plt.subplots(1, n + 2)
    fig.set_size_inches(W/100.0*n, H/100.0)

    plot_images = [copy.deepcopy(ori_image) for _ in range(n + 2)]
    mask_images = [np.zeros((H, W, 4)) for _ in range(n + 1)]
    for i, plot_img in enumerate(plot_images):
        axs[i].imshow(plot_img)
        axs[i].axis('off')

    for i, box_i in enumerate(bbox):
        color = np.random.random(3)
        box_color = np.concatenate([color, [1.0]])
        mask_color = np.concatenate([color, [0.4]])

        x_min, y_min, x_max, y_max = box_i
        width, height = x_max - x_min, y_max - y_min
        rect = plt.Rectangle((x_min, y_min), width, height, linewidth=2, edgecolor=box_color, facecolor='none')
        axs[0].add_patch(rect)

        mask_images[0][ori_mask[i].astype(bool)] = mask_color
        axs[1].imshow(mask_images[0])

        for j, batch_mask in enumerate(multi_masks):
            mask_ = batch_mask[b][i]
            mask_images[j + 1][mask_] = mask_color
            axs[j + 2].imshow(mask_images[j + 1])

    plt.subplots_adjust(wspace=0)
    plt.savefig(os.path.join(save_path, f"{image_id}.jpg"), dpi=300, bbox_inches='tight', pad_inches=0)
    plt.close(fig)
```

**Comment by ybk66** [comment]
Thank you for your reply. I have another question: How to use the trained SAM weight file to infer a single image?
I have observed that the format and number of blocks in the “**model**” key of the automatically saved “**.pth**” file are different from the original SAM, so it cannot be simply loaded through “**sam. load_stateDict()**”.

**Comment by zhang-haojie** [comment]
You can use the following code to load the weights file.
```
full_checkpoint = fabric.load(ckpt)
model.load_state_dict(full_checkpoint["model"])
```

**Comment by wanglian0701** [comment]
> You can use the following code to load the weights file.
> 
> ```
> full_checkpoint = fabric.load(ckpt)
> model.load_state_dict(full_checkpoint["model"])
> ```
"What is “fabric.load”? I get the error AttributeError: module 'fabric' has no attribute 'load' when I run the code."

**Comment by wanglian0701** [comment]
> 谢谢你的回复。我还有一个问题：如何使用经过训练的 SAM 权重文件来推断单个图像？我观察到自动保存的 “**.pth**” 文件的 “**model**” 键中的格式和块数与原始 SAM 不同，因此不能简单地通过 “**sam.load_stateDict（）**“的。

Could you please tell me if you have solved this problem? If so, how did you solve it?

**Comment by zhang-haojie** [comment]
> > 谢谢你的回复。我还有一个问题：如何使用经过训练的 SAM 权重文件来推断单个图像？我观察到自动保存的 “**.pth**” 文件的 “**model**” 键中的格式和块数与原始 SAM 不同，因此不能简单地通过 “**sam.load_stateDict（）**“的。
> 
> Could you please tell me if you have solved this problem? If so, how did you solve it?

My code framework is based on Lightning, so I wrapped the SAM model inside another `model`. Since the trained models are also saved as `model`, you could try saving `model.model`.
